### ISSUE TITLE
Delay move transition

### ISSUE THREAD

**Issue by soundprojects** [brofrain/leptos-animated-for#1]
Great crate! Thanks for all the work you put in

I tried adding tailwind transition delay to the elements but the delay is not applied when the items are moved when items are removed or added. Does the crate support delay?

**Comment by brofrain** [comment]
Hey,
thanks for opening the issue and sorry for the late response on my side.
I've been playing with delays a bit and the animations themself seem to work as expected. For example, adding `animate-spin animate-delay-2000` classes to the `leave_class` prop correctly caused elements to spin after 2 seconds.
Applying `transition-delay-2000 transition-1000` to `move_class` also prevented objects from moving for 2 seconds as expected. I've noticed a bug though that breaks element positioning when a list is reordered before its transition starts. I've opened a dedicated issue for that unwanted behavior: https://github.com/brofrain/leptos-animated-for/issues/2
Delayed leave transitions don't affect the time when non-removed elements move to newly abandoned positions, which is intentional behavior.

Could you provide me with a code sample, so I can better understand where the problem may be and how to fix / work around it?

**Comment by soundprojects** [comment]
Sure thing, so I tried your move classes like below:
`                            enter_class="lineUp"
                            leave_class="fadeOut1500"
                            move_class="transition-delay-2000 transition-1000"`

However, the items do move to their new position but the delay is not working here

**Comment by soundprojects** [comment]
Got it, added the css class with a definition. Thanks!
